version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - type: bind
        source: ./mysql-data
        target: /var/lib/mysql
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db
      MYSQL_USER: app
      MYSQL_PASSWORD: password
