DROP TABLE IF EXISTS textbook;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS textbook_comment;

CREATE TABLE textbook (
  isbn INTEGER PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  author TEXT NOT NULL
);

CREATE TABLE review (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  isbn INTEGER NOT NULL,
  score INTEGER NOT NULL
);

CREATE TABLE textbook_comment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  body TEXT NOT NULL
);
